Problem: redundant-connection-ii
Submission ID: 1695710313
Submission Time: 2025-07-12 15:43:56
============================================================

State: SUCCESS
Status: Accepted
Language: Python

Runtime: 7 ms
Memory: 12.74 MB

Test Cases: 57/57 passed

Runtime Percentile: 36.58550000000002%
Memory Percentile: 70.7318%

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 10,
  "lang": "python",
  "run_success": true,
  "status_runtime": "7 ms",
  "memory": 12740000,
  "display_runtime": "7",
  "question_id": "685",
  "elapsed_time": 42,
  "compare_result": "111111111111111111111111111111111111111111111111111111111",
  "code_output": "",
  "std_output": "",
  "last_testcase": "",
  "expected_output": "",
  "task_finish_time": 1752360233919,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 57,
  "total_testcases": 57,
  "runtime_percentile": 36.58550000000002,
  "status_memory": "12.7 MB",
  "memory_percentile": 70.7318,
  "pretty_lang": "Python",
  "submission_id": "1695710313",
  "status_msg": "Accepted",
  "state": "SUCCESS"
}