Problem: handling-sum-queries-after-update
Submission ID: 1695557933
Submission Time: 2025-07-12 11:34:07
============================================================

State: SUCCESS
Status: Accepted
Language: Python

Runtime: 1600 ms
Memory: 51.43 MB

Test Cases: 77/77 passed

Runtime Percentile: 33.33339999999999%
Memory Percentile: 33.33339999999999%

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 10,
  "lang": "python",
  "run_success": true,
  "status_runtime": "1600 ms",
  "memory": 51428000,
  "display_runtime": "1600",
  "question_id": "2703",
  "elapsed_time": 1744,
  "compare_result": "11111111111111111111111111111111111111111111111111111111111111111111111111111",
  "code_output": "",
  "std_output": "",
  "last_testcase": "",
  "expected_output": "",
  "task_finish_time": 1752345246888,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 77,
  "total_testcases": 77,
  "runtime_percentile": 33.33339999999999,
  "status_memory": "51.4 MB",
  "memory_percentile": 33.33339999999999,
  "pretty_lang": "Python",
  "submission_id": "1695557933",
  "status_msg": "Accepted",
  "state": "SUCCESS"
}