Problem: a-number-after-a-double-reversal
Submission ID: 1695545332
Submission Time: 2025-07-12 11:22:17
============================================================

State: SUCCESS
Status: Wrong Answer
Language: Python

Runtime: 0 ms
Memory: 12.58 MB

Test Cases: 1/129 passed

Last Test Case:
Input: 526
Expected: true

Code Output: 6

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 11,
  "lang": "python",
  "run_success": true,
  "status_runtime": "N/A",
  "memory": 12580000,
  "display_runtime": "0",
  "question_id": "2238",
  "elapsed_time": 34,
  "compare_result": "001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "code_output": "6",
  "std_output": "",
  "last_testcase": "526",
  "expected_output": "true",
  "task_finish_time": 1752344535946,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 1,
  "total_testcases": 129,
  "runtime_percentile": null,
  "status_memory": "N/A",
  "memory_percentile": null,
  "pretty_lang": "Python",
  "submission_id": "1695545332",
  "input_formatted": "526",
  "input": "526",
  "status_msg": "Wrong Answer",
  "state": "SUCCESS"
}