Problem: max-points-on-a-line
Submission ID: 1695615137
Submission Time: 2025-07-12 12:43:59
============================================================

State: SUCCESS
Status: Runtime Error
Language: Python

Runtime: N/A ms
Memory: 12.29 MB

Test Cases: 0/41 passed

Last Test Case:
Input: [[1,1],[2,2],[3,3]]
Expected: 3

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 15,
  "lang": "python",
  "run_success": false,
  "runtime_error": "Line 24: AttributeError: 'list' object has no attribute 'x'",
  "full_runtime_error": "AttributeError: 'list' object has no attribute 'x'\n    if start.x == end.x and start.y == end.y:\nLine 24 in maxPoints (Solution.py)\n    ret = Solution().maxPoints(param_1)\nLine 65 in _driver (Solution.py)\n    _driver()\nLine 79 in <module> (Solution.py)",
  "status_runtime": "N/A",
  "memory": 12292000,
  "question_id": "149",
  "elapsed_time": 32,
  "compare_result": "00000000000000000000000000000000000000000",
  "code_output": "",
  "std_output": "",
  "last_testcase": "[[1,1],[2,2],[3,3]]",
  "expected_output": "3",
  "task_finish_time": 1752349437159,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 0,
  "total_testcases": 41,
  "runtime_percentile": null,
  "status_memory": "N/A",
  "memory_percentile": null,
  "pretty_lang": "Python",
  "submission_id": "1695615137",
  "status_msg": "Runtime Error",
  "state": "SUCCESS"
}