Problem: coordinate-with-maximum-network-quality
Submission ID: 1695395538
Submission Time: 2025-07-12 21:26:34
============================================================

State: SUCCESS
Status: Runtime Error
Language: Python

Runtime: N/A ms
Memory: 12.48 MB

Test Cases: 4/101 passed

Last Test Case:
Input: [[42,0,0]]
7
Expected: [0,0]

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 15,
  "lang": "python",
  "run_success": false,
  "runtime_error": "Line 26: UnboundLocalError: local variable 'result' referenced before assignment",
  "full_runtime_error": "UnboundLocalError: local variable 'result' referenced before assignment\n    return result\nLine 26 in bestCoordinate (Solution.py)\n    ret = Solution().bestCoordinate(param_1, param_2)\nLine 57 in _driver (Solution.py)\n    _driver()\nLine 71 in <module> (Solution.py)",
  "status_runtime": "N/A",
  "memory": 12484000,
  "question_id": "1726",
  "elapsed_time": 31,
  "compare_result": "11110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "code_output": "",
  "std_output": "",
  "last_testcase": "[[42,0,0]]\n7",
  "expected_output": "[0,0]",
  "task_finish_time": 1752335787338,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 4,
  "total_testcases": 101,
  "runtime_percentile": null,
  "status_memory": "N/A",
  "memory_percentile": null,
  "pretty_lang": "Python",
  "submission_id": "1695395538",
  "status_msg": "Runtime Error",
  "state": "SUCCESS"
}